version: '3'

services:
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'jaC3R3GyYRrTC8gh'
      POSTGRES_USER: guacamole_user
    volumes:
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml
    depends_on:
      - guacd
      - postgres
    networks:
      - guacamole-net

  guacd:
    image: guacamole/guacd
    container_name: guacd
    ports:
      - "4822:4822"
    networks:
      - guacamole-net

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'jaC3R3GyYRrTC8gh'
      POSTGRES_USER: guacamole_user
    networks:
      - guacamole-net
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - postgresql_data:/var/lib/postgresql/data:Z

  rdesktop2:
    build: .
    networks:
      - guacamole-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3389:3389

networks:
  guacamole-net:

volumes:
  postgresql_data:

